# Root of COINES installation folder
# Can be C:/COINES/v2.2 , $(HOME)/COINES/v2.2 ,etc.,
# Don't use '\' 
COINES_INSTALL_PATH = ../..

EXAMPLE_FILE = template.c
# EXAMPLE_FILE = template.cpp

# Additional C files
# Eg: C_SRCS += support.c test.c
C_SRCS += 

# Additional C++ files
# Eg: CPP_SRCS += support.cpp test.cpp
CPP_SRCS += 

# Assembly source files. Take care of the processor architecture !
# Extension is '.S' not '.s'
# Eg: ASM_SRCS += support.S test.S
ASM_SRCS += 

# Additional paths to look for header files
# Eg: INCLUDEPATHS += inc inc/test
INCLUDEPATHS +=

# Additional C compiler flags
# Eg: CFLAGS += -D TEST=5 
CFLAGS +=

# Additional C++ compiler flags
# Eg: CPPFLAGS += -std=c++11 
CPPFLAGS +=

# Specify compiler optimization (Default -Os)
# Eg: OPT = -O0
OPT = -Os

# Debug enable(1)/disable(0) 
# Eg: DEBUG = 1 (Debug enable)
DEBUG = 0

# To enable Zeús board support, set ZEUS_QUIRK = 1
ZEUS_QUIRK = 0

# Additional paths to look for library files
LIBPATHS +=

# Additional static/shared libraries
# Eg: To include libraries, libalgobsec.a and libalgobsx.a
# LIBS += algobsec algobsx
LIBS +=

include $(COINES_INSTALL_PATH)/coines.mk
