COINES_INSTALL_PATH ?= ../../..

EXAMPLE_FILE = app_switch.c

override TARGET=PC

INCLUDEPATHS += \
$(COINES_INSTALL_PATH)/coines_api/pc \
$(COINES_INSTALL_PATH)/coines_api/pc/comm_driver \
$(COINES_INSTALL_PATH)/coines_api/pc/comm_intf \

include $(COINES_INSTALL_PATH)/coines.mk